-- This script sets up the initial database schema for the ATTN project.
-- Version 3, synchronized with non-optional Pydantic models.

-- Enable UUID generation functionality, which might be used by other tools or manual queries.
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: Users
-- Stores information about all users in the system (students and teachers).
CREATE TABLE Users (
    user_school_number TEXT PRIMARY KEY,       -- Unique identifier for each user, acting as the Primary Key.
    user_full_name TEXT NOT NULL,              -- Full name of the user.
    role TEXT NOT NULL                         -- Role of the user (e.g., 'teacher', 'student'), critical for authorization.
);

-- Table: Attendances
-- Represents a single attendance-taking session initiated by a teacher.
CREATE TABLE Attendances (
    attendance_id UUID PRIMARY KEY,            -- Unique identifier for the attendance session. UUIDs are generated by the application.
    teacher_school_number TEXT NOT NULL REFERENCES Users(user_school_number), -- Foreign Key linking to the teacher who started the session.
    lesson_name TEXT NOT NULL,                 -- Name of the lesson for the session.
    ip_address TEXT,                           -- IP address associated with the session. (Optional)
    start_time TIMESTAMP WITH TIME ZONE NOT NULL, -- The exact time the session started.
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,   -- The exact time the session ended.
    security_option INTEGER NOT NULL,          -- An integer representing security settings for the session.
    is_deleted BOOLEAN DEFAULT FALSE,          -- Flag for soft deletion.
    deletion_reason TEXT,                      -- Reason for the soft deletion. (Optional)
    deletion_time TIMESTAMP WITH TIME ZONE     -- The time of the soft deletion. (Optional)
);

-- Table: AttendanceRecords
-- Stores the record for each individual student for a specific attendance session.
CREATE TABLE AttendanceRecords (
    attendance_id UUID NOT NULL REFERENCES Attendances(attendance_id), -- Foreign Key linking to the specific attendance session.
    student_number TEXT NOT NULL REFERENCES Users(user_school_number), -- Foreign Key linking to the student.
    is_attended BOOLEAN DEFAULT FALSE,         -- Whether the student was marked as present. (Defaults to FALSE)
    attendance_time TIMESTAMP WITH TIME ZONE,  -- The time the student's attendance was recorded. (Optional)
    fail_reason TEXT,                          -- Reason for a failed attendance attempt. (Optional)
    is_deleted BOOLEAN DEFAULT FALSE,          -- Flag for soft deletion of a single record.
    deletion_reason TEXT,                      -- Reason for the soft deletion. (Optional)
    deletion_time TIMESTAMP WITH TIME ZONE,    -- The time of the soft deletion. (Optional)
    PRIMARY KEY (attendance_id, student_number) -- Composite Primary Key ensures a student has only one record per session.
);

-- Add indexes for frequently queried foreign key columns to improve JOIN performance.
CREATE INDEX idx_attendances_teacher_school_number ON Attendances(teacher_school_number);
CREATE INDEX idx_attendance_records_attendance_id ON AttendanceRecords(attendance_id);